### PR TITLE
Fix #287: Issue of MYSQL_OPT_SSL_MODE

### LINKED ISSUE #287: Issue of MYSQL_OPT_SSL_MODE
Currently there are many `#ifdef MYSQL_OPT_SSL_MODE` in `drv_mysql.c`.
https://github.com/akopytov/sysbench/blob/master/src/drivers/mysql/drv_mysql.c#L67

But where does this macro `MYSQL_OPT_SSL_MODE` be defined? In `mysql.h`, it is only a value of enum.
I don't think all compilers can recognize this.

In my test environment:
```
Ubuntu 18.04.1 LTS
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
libmysqlclient-dev/bionic-updates,bionic-security,now 5.7.24-0ubuntu0.18.04.1 amd64 [installed]
```
The compilation won't go into the #ifdef blocks, and the sysbench built has SSL issues.
Also, the output of `sysbench --help` contains the wrong parameter:
`--mysql-ssl[=on|off]             use SSL connections, if available in the client library [off]`

### PR DESCRIPTION
**Pull request by akopytov**
In drv_mysql.c do not assume MYSQL_OPT_SSL_MODE to be a preprocessor
define. It is an mysql_option enum value with all MySQL
versions. Instead, do a configure-time check if that value is defined in
mysql.h.

### CODE REVIEW

File: src/drivers/mysql/drv_mysql.c [hunk 1]
```diff
@@ -323,10 +323,10 @@ static int mysql_drv_real_connect(db_mysql_conn_t *db_mysql_con)
 
     mysql_ssl_set(con, ssl_key, ssl_cert, ssl_ca, NULL, args.ssl_cipher);
 
-#ifdef MYSQL_OPT_SSL_MODE
```
Comment (wujysh) [inline src/drivers/mysql/drv_mysql.c]: There are many other `#ifdef MYSQL_OPT_SSL_MODE` in this file.

Comment (wujysh) [reply src/drivers/mysql/drv_mysql.c]: OK, this is branch 1.0.

Comment (akopytov) [reply src/drivers/mysql/drv_mysql.c]: Yes, this is a 1.0 PR.
